{% set name = "cvasl" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/brainspinner/{{ name }}.git
  git_rev: "pyproject"
  git_depth: 1

  # url: https://github.com/brainspinner/cvasl/archive/v{{ version }}.tar.gz
  # sha256: 239403e4937e9b4854f60b979ac4ca0eb4eb57aa39c449c6c095a8385814ee45

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >=3.10
    - setuptools >=64.0.0
    - setuptools-scm >=8
    - wheel
    - python-build
    - pip
  run:
    - python
    - ipympl
    - jupyter
    - jupyterlab
    - kneed
    - matplotlib
    - matplotlib-inline
    - nibabel
    - notebook
    - numpy<2
    - pandas>=1.2.0
    - patsy
    - pip
    - pycodestyle
    - pydicom
    - pytest
    - pyxdf
    - scikit-image
    - scikit-learn>=0.23.2
    - scipy>=1.5.4
    - seaborn
    - simpleitk>=2.0.1
    - tqdm>=4.59
    - umap-learn>=0.5.1
    - yellowbrick>=1.3

test:
  imports:
    - {{ name|lower }}
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A package for analysis of MRI
  license: MIT AND Unlicense AND Apache-2.0
  license_file:
    - LICENSE
    - NOTICE.md
    - cvasl/vendor/comscan/LICENSE
    - cvasl/vendor/neurocombat/LICENSE
    - cvasl/vendor/open_nested_combat/LICENSE

extra:
  recipe-maintainers:
    - suvayu
