name: Release

on:
  push:
    tags:
      - v*
# on: [push]

jobs:
  PyPIBuild:
    if: ${{ github.repository == 'brainspinner/cvasl' }}
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
        # Unfortunately, wheel will try to do setup.py install to
        # build a wheel... and we need this stuff to be able to build
        # for CPython.
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11
      - run: python3.11 -m venv .venv
      - run: .venv/bin/python -m pip install wheel twine
      - run: .venv/bin/python setup.py bdist_wheel

  CondaBuild:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    # defaults:
    #   run:
    #     shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11]
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - { os: windows-latest, shell: msys2 }
          - { os: ubuntu-latest,  shell: bash  }
          - { os: macos-latest,   shell: bash  }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: ci
          channels: conda-forge
      - run: conda config --remove channels defaults
      - name: Generate conda meta.yaml (Python 3.11)
        run: python -u setup.py anaconda_gen_meta
      - run: python -u setup.py bdist_conda


  PublishArtifacts:
    runs-on: ubuntu-latest
    needs: [PyPIBuild, CondaBuild]
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: dist
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUBTOKEN }}"
          prerelease: false
          files: |

            ./dist/pypi-build/*.whl

